- 01_primitive-data/1-02_managing-whitespace.asciidoc
\f is form feed, which is a different concept (more a page break than anything
else). \n can be referred to as newline or linefeed.
Let me know if I've screwed anything up; this tripped one of our developers
up when we were looking into some linefeed issues :)
> Fix mislabeling of \f as linefeed.

- script/asciidoc/bootstrap.sh
The command
pacman install
is not correct, the correct command is
pacman -S
The `--noconfirm` option is not necessary, it only bypassas any and all “Are you sure?” messages.
> correct the pacman arguments and add "--noconfirm" option

- 01_primitive-data/1-20_simple-statistics.asciidoc
Both group-by and frequencies produce maps. I think it's easier for the readers to comprehend by using the map entry manipulating functions (val/key) rather than the general purpose functions (second/first).
> Use val/key instead of second/first in simple-statistics recipe.

- 02_composite-data/2-09_get-item-at-index.asciidoc
The function **get** returns **nil**, not the keyword **:nil**. Should be a typo.
> Fix a typo in 2-09_get-item-at-index.asciidoc

- 02_composite-data/2-20_as-sequences.asciidoc
The result for **(first {:a 1 :b 2})** is not predictable and I find the code snippet works differently for me (**(key entry)** returns :b and **(val entry)** returns 2). It's also ok to use a sorted map but I think it's a good place to introduce the function **find** as it's not explained elsewhere.
> Use find instead of first to produce predictable result in 2-20_as-sequences.asciidoc

- 03_general-computing/3-05_main/3-05_main.asciidoc
The name space is **foo**, not **foo.core**.
> Fix an ns name in 3-05_main.asciidoc

- 00_frontmatter/conventions.asciidoc
- 03_general-computing/3-02_interactive-docs.asciidoc
- 03_general-computing/3-03_exploring-namespaces.asciidoc
As discussed in #445, highlight the REPL-only code snippets as text.
I think I've managed to find out all the REPL-only snippets, but those mixed with shell code and repl sessions can still be problematic. I've no idea how to deal with this and just leave them untouched. Below is an example taken from 4-15_edn-config.asciidoc:
> Highlight REPL-only code as text instead of shell-session.

- 03_general-computing/3-07_parse-command-line-arguments.asciidoc
The original code doesn't work and throws the ClassCastException. :assoc-fn, as indicated by it's name, should be able to assoc the value to a map.
> Correct the :assoc-fn in 3-07_par...ments.asciidoc

- 09_distributed-computation/9-00_introduction.asciidoc
- 09_distributed-computation/9-01_stream-processing.asciidoc
Both http://storm-project.net and http://storm.incubator.apache.org now redirect to http://storm.apache.org.
> Update storm homepage links.

- 03_general-computing/3-13_core-logic.asciidoc
This piece of code seems to be copied from the previous function. But it doesn't work when copy-and-pasted to an repl because the symbol **graph** is not a param of a function and not passed the value of **movie-graph**.
> Fix an unbound symbol in 3.13

- 04_local-io/4-13_parallelizing-file-processing-using-iota.asciidoc
As **(partial inc)** equals to **inc**, there's no need to use the former.
> Remove unneccessary call to partial in 4.13

- 04_local-io/4-09_read-write-files.asciidoc
1. "my stuff" is **spit**ed but "all my stuff" is **slurp**ed.
2. Unmatched parens.
> Minor corrections in 4.09

- 04_local-io/4-22_read-write-xml.asciidoc
**xml-seq** is in the **clojure.core** ns, not the **clojure.xml** ns.
As this is the only place where the alias of the ns is used, I removed the **:as** option in the **require**  call.
> Fix a wrong ns in 4.22

- 03_general-computing/3-09_polymorphism-with-protocols.asciidoc
The code describes math functions consistent with a rectangle, and not those of a parallelogram. To make the code match a parallelogram we would need a third variable representing the side length. This change is much smaller.
> Change reify comment to match code

- 05_network-io/5-07_communicating-with-mqtt.asciidoc
The library machine_head has [changed](https://github.com/clojurewerkz/machine_head/blob/master/ChangeLog.md#subscription-api-change) its Subscription API in the latest version. The old code no longer works and throws the ClassCastException.
> Update the MQTT recipe to follow the upstream API Change in 5.07

- 06_databases/6-04_korma.asciidoc
The **korma.core/values** function accepts one less argument when surrounded by the **korma.core/insert** function because the latter supplies one.
> Fix an ArityException in 6.04

- 06_databases/6-06_indexing-with-elasticsearch.asciidoc
1. Redundant parens.
2. My main purpose is to correct the index name (people) to the actually used one (test4). But the output in my REPL turned out to be different to the texted one, not sure if it's because of a different version of ElasticSearch.
3. The symbol **doc** conflicts with **clojure.repl/doc** when executed in the REPL.
4. The alias of **clojurewerkz.elastisch.rest.document** here is **esd**. There's also an **esr/put**(**clojurewerkz.elastisch.rest/put**) but it takes totally different args and works differently.
> Several fixes in 6.06

- 04_local-io/4-17_unknown-reader-literals.asciidoc
It took me a long time to figure out why clojure.edn/read didn't heed
data_readers.clj. (Because it's not supposed to.) Looking for answers,
recipe 4-17 turned up quite high in the search results, but didn't help
me much. When I finally figured it out, I hit my head against the wall
and suspected that other people have the same problems. So I added a
note to the ClojureDocs entry for clojure.edn/read.
Add a link to the ClojureDocs entry to the See Also section of recipe
4-17, so that people finding this recipe first, can achieve
enlightenment more quickly.
> 4-17 Unknown Tagged Literals: Add a See Also item

- 07_webapps/7-12_templating-with-selmer.asciidoc
I can't find anything about this kind of usage of "require": *(require '[selmer.filters/add-filter!])*, and this throws the FileNotFoundException. So I changed it to the :refer way.
By the way, add the function "render" to the refer list as it's used later.
> Fix a require statement in 7.12 

- 07_webapps/7-14_markdown.asciidoc
1. Require **clojure.java.io** for **input-stream** and **output-stream**.
2. Unmatched double quote mark.
3. **markdown.core** is aliased to **md** than **markdown** here.
> Several fixes in 7.14

- 08_deployment-and-distribution/8-06_primitive-arrays.asciidoc
hiphip.float/reduce -> hiphip.float/**a**reduce
> Fix a macro name in 8.06

- 04_local-io/4-13_parallelizing-file-processing-using-iota.asciidoc
The example uses `iota` instead of `io` as the namespace alias:
```clj
;; Main file processing
(defn keyword-count
"Returns a map of the word counts"
[filename]
(->> (iota/seq filename)
(r/filter identity)
(r/map count-map)
(r/fold add-maps)))
```
> Fix typo in namespace alias
